# Generated by Django 6.0.3 on 2026-03-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_alter_business_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
